### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by Louis345** [Sainglend/tda-api-client#10]
First, thank you for this library it seems great. I'm just having an issue with authentication. I'm receiving a 403 when trying to do authenticated requests. Any ideas on how should approach trying to solve this issue? I tried my best to follow the instructions and everything seemed to work, so I'm a bit in the dark.

**Comment by Sainglend** [comment]
Hi Louis, I'm curious how far you got with the instructions. It sounds like you made it all the way to the step of getting your refresh_token and tried a request with that?
One thing to try is this: In that auth readme, there is a section titled "DONE!!!! Sort of..."
https://github.com/Sainglend/tda-api-client/blob/master/authREADME.md#done-sort-of

Try those steps and see if you get a result. If you do, then that means your refresh_token is valid and working, and we can try something else.
If that doesn't work, then that means you didn't get a valid refresh_token.

**Comment by Louis345** [comment]
I was able to get a refresh_token at least I think it worked. I will repeat the instructions and report back. Thank you so much for your prompt response.

**Comment by Sainglend** [comment]
Yeah what I was asking is what you did after getting that token. The other set of steps I encouraged you to try was to then take that refresh_token and use that tda auth form webpage to try to generate an access_token.

So, two steps:
1. Do the many steps to get a refresh_token, ending with using this webpage: https://developer.tdameritrade.com/authentication/apis/post/token-0. You did that.

2. With the refresh_token, you should just be able to use the library. However, verify that you can use that refresh_token to generate an access_token by again visiting the same webpage (https://developer.tdameritrade.com/authentication/apis/post/token-0), but this time filling in different inputs. If you can't generate an access_token, then we've pinpointed the problem.

**Comment by Sainglend** [comment]
pupup

**Comment by Louis345** [comment]
Hello,


I followed all the instructions and I'm almost positive that the refresh_token works. I went to this url: `https://developer.tdameritrade.com/authentication/apis/post/token-0`  and I was able to retrieve a refresh_token  with a scope of `  "scope": "PlaceTrades AccountAccess MoveMoney",` and I was able to use the library to get the OptionChain to work. However, whenever I try to query my TD account I get this error:`ERROR [401]: {"error": "The API key in request is either null or blank or invalid."}'`. I'm really confused about what I'm doing wrong. I did test it using the second step you mentioned up above and I was able to get an access_token.   Thank you again for helping me resolve this issue.

**Comment by Louis345** [comment]
Just to be clear I was able to take my refresh_token and generate an access token so I'm really baffled on why I'm not able to make authenticated requests.

**Comment by Louis345** [comment]
@Sainglend  So I was able to get this to work `const authConfig = await tdaclient.authentication.getAuthentication()` 
it returned an object with the following keys: refresh_token, client_id, and access_token so I appear that I am in fact authenticated. I suspect that I'm using the library incorrectly.  When I copy a code sample there is a key with an accountId propery and it's always set to 1,  what value should be in the accountId?  Maybe that is my issue?

**Comment by Louis345** [comment]
I solved my issue it was the accountId. I didn't know I had to get my accountId on my settings page. It's working now. I think for newbies like myself maybe adding verbiage on how to get your accountId might help people. I would gladly open a pull request if you think it might add value.

**Comment by Sainglend** [comment]
> I solved my issue it was the accountId. I didn't know I had to get my accountId on my settings page. It's working now. I think for newbies like myself maybe adding verbiage on how to get your accountId might help people. I would gladly open a pull request if you think it might add value.

By all means! Thanks! I'm happy you could figure out the issue.
