### ISSUE TITLE
Unable to register developer account.

### ISSUE THREAD

**Issue by pursual** [Sainglend/tda-api-client#11]
No matter what I enter for username at developer.tdameritrade.com, it gives me the error "Username format is invalid". Any suggestions?

**Comment by Louis345** [comment]
I ran into this issue before. What I did to solve was use another email address that was not connected to my TD Account. I think the API has poor error handling. Try a different email address that is not associated with your TD account. That should resolve the issue.

**Comment by pursual** [comment]
Wow, if I pick a username that matches one of my trading accounts, it works... smh.

Thanks.
