### ISSUE TITLE
Error ECONNRESET

### ISSUE THREAD

**Issue by lordscruffo** [Sainglend/tda-api-client#3]
It looks like i'm getting this error:

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

any thoughts.    It works fine after hours,  but during trading times,  i'm getting this guy.

**Comment by karann7** [comment]
> It looks like i'm getting this error:
> 
> Error: read ECONNRESET
> at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
> errno: -4077,
> code: 'ECONNRESET',
> syscall: 'read'
> }
> 
> any thoughts. It works fine after hours, but during trading times, i'm getting this guy.


Hey there! So I am having this same exact issue after I place an order the whole app freezes and no other commands work. Have to restart the app for normal functionality. 
however other requests like quotes and account stuff works just fine. 

Let me know if you figured out what the issue was and what I can do to fix. Thank you.

**Comment by TonyVeigel** [comment]
@karann7  Had same issue so switched to using Axios and it works fine

**Comment by karann7** [comment]
> @karann7 Had same issue so switched to using Axios and it works fine

can you help me understand how i can use Axios to make the requests to the API. i have my auth token but when i try to pass in params to axios the request doesn't go through. if you code paste below like a axios request to place order and what i need to pass inside it that would be awesome.

**Comment by TonyVeigel** [comment]
@karann7 

```
const apiWriteResource = async (config, method) => {
    
    const authResponse = await auth.api.getAuthentication(config);
    const token = authResponse.access_token;

    const requestOptions = {
        method: method,
        headers: {}
    };
    const postData = JSON.stringify(config.bodyJSON);
    requestOptions.headers['Content-Length'] = postData.length;
    requestOptions.headers['Content-Type'] = 'application/json';

    if (!config.apikey) {
        requestOptions.headers['Authorization'] = `Bearer ${token}`;
    }

    requestOptions.data = postData
    requestOptions.url = 'https://api.tdameritrade.com' + config.path

    return axios(requestOptions)
        .then(resp => {
            return resp;
        })
        .catch(err => {
            console.log(err)
            return err;
        })
    
    };
```

**Comment by Sainglend** [comment]
I've switched to using axios and pushed up v1.0.1
